// This is a Java comment (important for your future self)
// JVM Java Virtual Machine

// javac Hello.java (creates the Hello.class file)
// java Hello

// java Hello.java (new way to run a Java program)

/*
 * A class is a blueprint that defines the variables and the methods commom
 * to all objects of a certain kind
 *
 * Bytecode is a machine-independent code generated by the Java compiler and
 * executed by the interpreter
 */

public class Hello {
  public static void main(String[] args) {
    System.out.println("Hello Java");
  }
}
