// Intro - Hello World

// javac HelloWorld.java -> HelloWorld.class
// java HelloWorld

// java HelloWorld.java (only when you have 1 class in your file)

/*
 * A class is a blueprint that defines the variables and methods commom to all
 * objects of a certain kind
 *
 * .class -> bytecode - generated by the Java compiler and executed by the
 * interpreter
 */

public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello world");
  }
}
